# Generated by Django 4.2.3 on 2023-09-08 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etudiantAuthent', '0002_alter_comment_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
    ]
